version: '3'
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
  balancer:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app1
      - app2